### ISSUE TITLE
C60 from mol2 file 

### ISSUE THREAD

**Issue by theonov13** [pyflosic/fodMC#10]
It seems that there is a problem. 
Please check and verify.

**Comment by kaitrepte** [comment]
Hi.
The problem is that the bonding information provided in the mol file is incompatible with a fodMC input. Some of the C atoms are characterized by having 3 bonds. With that, they will automatically have  a single lone FOD attached to them. This is why you see 10 spin-up lone FODs floating around. This might be very difficult to fix right away.
